USE class;
DELETE FROM Adds;
DELETE FROM Bots;
DELETE FROM Manages;
DELETE FROM Botnet_Order;
DELETE FROM Affiliates;
DELETE FROM Support_Staff;
DELETE FROM Support_Tickets;
DELETE FROM Interface;
DELETE FROM User;